export const PLAY = 'PLAY'
export const PLAY_ERROR = 'PLAY_ERROR'
export const PLAY_SUCCESS = 'PLAY_SUCCESS'
export const PROCESSING = 'PROCESSING'
export const RESUME = 'RESUME'
export const PAUSE = 'PAUSE'
export const UPDATE = 'UPDATE'
export const STOP = 'STOP'